# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:
  first:              UNDER
  span:               L
  last:               INE.SCSS

tagline:             A Medium-Like Underline (SCSS Mixin)
description:         UNDERLINE.SCSS - A carefully crafted, pixel-perfect, medium-like underline
url:                 http://benkalsky.net/underline.scss
baseurl:             ''
#paginate:            5

github:
  repo: https://github.com/benkalsky/underline.scss

sass:
  style: :expanded

# About/contact
author:
  name:              Ben Kalsky
  url:               https://twitter.com/benkalsky
  email:             benkalsky@gmail.com

# Custom vars
version:             1.0.0

gems:
#  - jekyll-paginate
